# Generated by Django 5.1.1 on 2024-09-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-id'], 'verbose_name': 'автомобиль', 'verbose_name_plural': 'автомобили'},
        ),
    ]
